[project]
name = "Enviroplus Monitor"
version = "0.1.0"
description = "Publish measurements from a Pimoroni Enviro+ hat"
authors = [
    "Philip Cutler <[email protected]>"
]
license = "MIT"
readme = "README.md"
python = "^3.7"
homepage = "https://github.com/greenthegarden/enviroplus-monitor"
repository = "https://github.com/greenthegarden/enviroplus-monitor"
documentation = "https://github.com/greenthegarden/enviroplus-monitor"

keywords = ["monitoring", "mqtt", "influxdb", "sensors"]

classifiers = [
    "Topic :: Sensor Monitoring"
]

# Requirements
[dependencies]
Click = "^7.0"

[dev-dependencies]
black = { version = "^18.3-alpha.0", python = "^3.7" }

[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = [
    "setuptools>=40.8.0"
]
build-backend = "setuptools.build_meta"
