---

schema:

  configPayload:
    type: object
    properties:
      device_class:
        type: string
        description: Class of sensor measurement
        default: temperature
      name:
        type: string
        description: Name of sensor measurement
        default: Temperature
      state_topic:
        type: string
        description: State topic
        default: STATE_TOPIC
      unit_of_measurement:
        type: string
        description: Units of sensor measurement
        default: "°C"
      value_template:
        type: string
        description: Value template for sensor measurement
        default: "{{ value_json.temperature}}"
  measurement:
    type: object
    properties:
      label:
        type: string
        description: Label for measurement
      value:
        type: number
        description: Value of measurement
      units:
        type: string
        description: Units of measurement
  bme280Measurement:
    type: object
    properties:
      sensor: 
        type: string
        description: Sensor type
        default: 'configurationhandler.config["sensors"]["WEATHER_LABEL"]'
      measurements:
        type: array
        description: Measurement array
        items: [ {
          $ref: '#/components/schemas/measurement'
          }
        ]
  bme280MeasurementPayload:
    type: object
    properties:
      temperature:
        type: number
      humidity:
        type: number
        minimum: 0
        maximum: 100
      pressure:
        type: number
