type: object
properties:
  device_class:
    type: string
    description: Class of sensor measurement
  name:
    type: string
    description: Name of sensor measurement
  state_topic:
    type: string
    description: State topic
  unit_of_measurement:
    type: string
    description: Units of sensor measurement
  value_template:
    type: string
    description: Value template for sensor measurement
