$id: configPayload.yaml
$schema: "http://json-schema.org/draft-07/schema#"
title: measureRecord
description: Configuration payload conforming to home assistant requirements
type: object
properties:
  device_class:
    type: string
    description: Class of sensor measurement
  name:
    type: string
    description: Name of sensor measurement
  state_topic:
    type: string
    description: State topic
  unit_of_measurement:
    type: string
    description: Units of sensor measurement
  value_template:
    type: string
    description: Value template for sensor measurement
required:
  - device_class
  - name
  - state_topic
  - unit_of_measurement
  - value_template
